config/routes.rb
Rails.application.routes.draw do
  resources :blog_posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    has_many :likes, dependent: :destroy
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :blog_post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: %i[ show edit update destroy ]

  # GET /blog_posts or /blog_posts.json
  def index
    @blog_posts = BlogPost.all.order(id: :desc)
  end

  # GET /blog_posts/1 or /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts or /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
          format.turbo_stream do
              render turbo_stream: [
                turbo_stream.prepend("blog_posts", partial: "blog_post", locals: { blog_post: @blog_post })
              ]
          end
          # Fall back for browser with javascript disabled
          format.html { redirect_to blog_posts_path, notice: "Blog post was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1 or /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to blog_posts_path, notice: "Blog post was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1 or /blog_posts/1.json
  def destroy
    @blog_post.destroy!

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@blog_post) }
      # Fall back for browser with javascript disabled
      format.html { redirect_to blog_posts_path, notice: "Blog post was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_post_params
      params.require(:blog_post).permit(:author, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/_blog_post.html.erb
<div id="<%= dom_id blog_post %>" >
  <%= turbo_frame_tag dom_id(blog_post) do %>
    <p class="my-5">
      <strong class="block font-medium mb-1">Author:</strong>
      <%= blog_post.author %>
    </p>
    <p class="my-5">
      <strong class="block font-medium mb-1">Content:</strong>
      <%= blog_post.content %>
    </p>
    <%= link_to "Edit", edit_blog_post_path(blog_post), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Delete", blog_post_path(blog_post), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <hr class="mt-6">
  <% end %>
</div>

app/views/blog_posts/_form.html.erb
<%= form_with(model: blog_post, class: "contents", data: {controller: "blog-form", blog_form_target: "formContainer"}) do |form| %>
  <% if blog_post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>
      <ul>
        <% blog_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-5" >
    <%= form.label :author %>
    <%= form.text_field :author, data: {action: "input->blog-form#handleChange", blog_form_target: "authorName"}, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <div class="flex flex-col gap-2">
      <span class="text-red-500 hidden" data-blog-form-target="authorBlank">
        Author name can't be blank
      </span>
      <span class="text-red-500 hidden" data-blog-form-target="authorLimitExceeded">
        Author name can't exceed more than 10 characters
      </span>
      <span class="text-red-500 hidden" data-blog-form-target="authorSpecialChar">
        Author name should not have any special characters
      </span>
    </div>
  </div>
  <div class="my-5">
    <%= form.label :content %>
    <%= form.text_area :content, data: {action: "input->blog-form#handleChange", blog_form_target: "blogContent"}, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <div class="flex flex-col gap-2">
      <span class="text-red-500 hidden" data-blog-form-target="contentBlank">
        Content can't be blank
      </span>
    </div>
  </div>
  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing blog post</h1>

   <%= turbo_frame_tag dom_id(@blog_post) do %>
      <%= render "form", blog_post: @blog_post %>
      <%= link_to "Back to blog posts", blog_posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
   <%end%>
</div>

app/views/blog_posts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <%= turbo_frame_tag "create-new-blog-post" do %>
    <div class="flex justify-between items-center" >
      <h1 class="font-bold text-4xl">Blogs</h1>
      <%= link_to "New blog post", new_blog_post_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>
  <% end %>
  <div id="blog_posts" class="min-w-full">
    <%= render @blog_posts %>
  </div>
</div>

app/views/blog_posts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New blog post</h1>
  <%# This frame will be replaced with the frame having this id %>
  <%= turbo_frame_tag "create-new-blog-post" do %>
    <%= render "form", blog_post: @blog_post %>
    <%= link_to "Back", blog_posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%end%>
</div>

app/views/blog_posts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @blog_post %>

    <%= link_to "Edit this blog_post", edit_blog_post_path(@blog_post), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this blog_post", blog_post_path(@blog_post), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to blog_posts", blog_posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lego</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>